# print('Merhaba Dünya')
#print ('Phyton ile ilk günüm!')
#print("Fonksiyon şu şekilde tanımlanır: print('ekrana yazdırılacak yazı)")
# print("Merhaba Dünya\nMerhaba Dünya\nMerhaba Dünya\n")
# print("Merhaba Dünya")
# print("Merhaba Dünya")
# print("Merhaba Dünya")
# print("Merhaba"+" "+"Şahin")
# print(input("Merhaba, Adın Nedir?"))
# print("Merhaba " + input("Merhaba,Adın Nedir?") + "!")
# print("a " + input("Kaç Yaşındasın?")+ "!")
# print("a " + input("Kaç Yaşındasın?")+ "!")
# print("a " + input("Kaç Yaşındasın?")+ "!")
# print(len(input("Merhaba, Adın Nedir?")))
# print(len(input("Merhaba, Adın Nedir?")))
# name = input("Merhaba Adın Nedir?")
# print(name)
# name = input("Merhaba, Kaç Yaşındasın")
# print(age)
# name = "İbrahim"
# print("name")
# name = "Özgür"
# print(name)
# name = "Şahin"
# print(name)
# name = "Taşın"
# print(name)
# print(len(input("Merhaba,Adın Nedir?")))
# isim = input("Merhaba,Adın Nedir?")
# uzunluk = len(isim)
# print(uzunluk)
# print(len(input("Merhaba,Adın Nedir?")))
# isim = input("Merhaba,Adın Nedir?")
# uzunluk = len(isim)
# print (uzunluk)
# Sayi1 = input("1inci Sayıyı Giriniz:")
# Sayi2 = input("2nci Sayıyı Giriniz")
# Sayi3 = Sayi1
# Sayi1 = Sayi2
# Sayi2 = Sayi3
# print("Sayi1 : " + Sayi1)
# print("Sayi2 : " + Sayi2)
# sayi1 = input("1nci Sayiyi Giriniz:")
# sayi2 = input("2nci Sayıyı Giriniz")
# sayi2 = sayi1
# print("sayi1 : " + sayi1)
# print("sayi2 : " + sayi2)
# isim_soyisim = input("İsim Soyisim")
# print("İsim Soyisim : " + isim_soyisim)
# print(str(1234567890))
# print(123 + 456)
# print(123_456_789)
# print("123_456_789")p
# print(1 - 2)
# print(3.12345)
print(True)
print(False)
